openapi: 3.1.0
info:
  title: Java API Exercise - Core Criteria
  description: Java API MVC in Memory Exercise - Core Criteria
  version: 0.2.3
  contact:
    name: MVC in Memory Exercise


servers:
  - url: http://localhost:4000
tags:
  - name: products
paths:
  /products:
    post:
      tags:
        - products
      operationId: createProduct
      summary: Create a product
      description: Add a new product to our list of available products
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateProduct'
      responses:
        '201':
          description: Product created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
    get:
      tags:
        - products
      summary: Get all products
      description: Get all of the products from our list
      operationId: getProducts
      responses:
        '200':
          description: Get all products
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AllProducts'
  /products/{id}:
    get:
      tags:
        - products
      summary: Get a product
      description: Get a product by ID
      operationId: getSpecificProduct
      parameters:
        - name: id
          in: path
          description: The ID of the product to get
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Get a specific product from the list given its ID
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
    put:
      tags:
        - products
      summary: Update a product
      description: Update an existing product by ID
      operationId: updateProduct
      parameters:
        - name: id
          in: path
          description: The ID of the product to update
          required: true
          schema:
            type: integer
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateProduct'
      responses:
        '201':
          description: Update the given product
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
    delete:
      tags:
        - products
      summary: Delete a product
      description: Remove a product from our list of products
      operationId: deleteProduct
      parameters:
        - name: id
          in: path
          description: The ID of the product to delete
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Delete the given product
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'

components:
  schemas:
    CreateProduct:
      type: object
      required: [name, category, price]
      properties:
        name:
          type: string
          example: "How to build APIs"
        category:
          type: string
          example: "Book"
        price:
          type: integer
          example: 1500
    Product:
      type: object
      properties:
        id:
          type: integer
          example: 1
        name:
          type: string
          example: "How to build APIs"
        category:
          type: string
          example: "Book"
        price:
          type: integer
          example: 1500
    AllProducts:
      type: array
      items:
        $ref: '#/components/schemas/Product'
